### ISSUE TITLE
Giscus not working

### ISSUE THREAD

**Issue by shrampoo** [Nsttt/my-portfolio#43]
Hey there! I found the RSC article interesting and well written, thanks for creating it.

I'm not sure if I'm missing anything, but it looks to me like the `giscus` integration is not working.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/123834935/227973874-a34492ef-6fb8-4a3a-aa6e-73ef29a28496.png">

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/123834935/227973766-8296479c-235c-4840-9a4d-ad4a1f679ad3.png">

I see similar errors on your [hello world post](https://nstlopez.com/blog/hello-world) as well. 

Let me know if I can help any further, thanks!

**Comment by Nsttt** [comment]
Hey thanks for the heads up. I'll investigate why this happens.
